{
  imports = [
    ./hardware/monitors.nix
    ./hardware/audio.nix
    ./desktop/fonts.nix
    ./desktop/fireproof-shell.nix
    ./desktop/greetd.nix
    ./desktop/hyprland/default.nix
    ./desktop/gtk/default.nix
    ./desktop/qt.nix
    ./apps/spotify.nix
    ./apps/firefox.nix
    ./apps/chromium.nix
    ./apps/ghostty.nix
    ./apps/slack.nix
    ./apps/obsidian.nix
    ./apps/claude.nix
  ];
}
