#!/bin/sh
hyprctl activewindow -j | jq --raw-output .title | sed 's/\(.\{120\}\).*/\1.../'
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 awk -F '>>|,' '/^activewindow>>/{print $3}' | sed 's/\(.\{120\}\).*/\1.../'
