#!/bin/bash

spaces (){
	hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .}) | from_entries' -Mc
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done