#!/usr/bin/env bash

hyprctl monitors -j | jq '.[] | select(.focused) | .name'

socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
  stdbuf -o0 awk -F '>>|,' -e '/^focusedmon>>/ {print $2}'