{
  imports = [
    ./hardware/monitors.nix
    ./hardware/audio.nix
    ./desktop/fonts.nix
    ./desktop/greetd.nix
    ./desktop/niri.nix
    ./desktop/gtk/default.nix
    ./desktop/qt.nix
    ./desktop/dms/default.nix
    ./desktop/screenshot.nix
    ./apps/spotify.nix
    ./apps/firefox.nix
    ./apps/chromium.nix
    ./apps/zed.nix
    ./apps/ghostty.nix
    ./apps/slack.nix
    ./apps/obsidian.nix
    ./apps/ferdium.nix
  ];
}
