name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Check formatting
        run: nix fmt -- --fail-on-change

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://nix-community.cachix.org https://fnug.cachix.org https://niri.cachix.org https://0xcbmedia.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= fnug.cachix.org-1:SDUeF2nZSbSPOAMNJdYZdoVB+tHdB8UHHcqhEmizeNk= niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964= 0xcbmedia.cachix.org-1:u8PfgqbbO/hjnsA77TCxi5w7hh82dApsqJ4bAgg9Rmo=

      - name: Run nix flake check
        run: nix flake check

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [desktop, laptop, work, homelab, desktop-wsl, minilab]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://nix-community.cachix.org https://fnug.cachix.org https://niri.cachix.org https://0xcbmedia.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= fnug.cachix.org-1:SDUeF2nZSbSPOAMNJdYZdoVB+tHdB8UHHcqhEmizeNk= niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964= 0xcbmedia.cachix.org-1:u8PfgqbbO/hjnsA77TCxi5w7hh82dApsqJ4bAgg9Rmo=

      - uses: ryanccn/attic-action@v0
        with:
          endpoint: https://attic.${{ secrets.HOMELAB_DOMAIN }}/
          cache: nixos
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
